services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teddy-backoffice-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env.docker
    environment:
      - DB_HOST_READ_WRITE=postgres
      - DB_HOST_READ_ONLY=postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm run start:dev"

  postgres:
    image: postgres:16-alpine
    container_name: teddy-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=teddy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=teddy_core
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    